export { ChatsPageController } from './ChatsPage.controller'
export { ErrorPageController } from './ErrorPage.controller'
export { LoginPageController } from './loginPage.controller'
export { RegistrationPageController } from './RegistrationPage.controller'
export { UserListController } from './UserList.controller'
